export const apiPath = {
  BANNERS: "/QuanLyPhim/LayDanhSachBanner",
  MOVIES: "/QuanLyPhim/LayDanhSachPhim",
  CINEMAS: "/QuanLyRap/LayThongTinHeThongRap",
  CINEMA_SCHEDULE: "/QuanLyRap/LayThongTinLichChieuHeThongRap",
  MOVIE_DETAIL: "/QuanLyRap/LayThongTinLichChieuPhim",
  LOGIN: "/QuanLyNguoiDung/DangNhap",
  SIGNUP: "/QuanLyNguoiDung/DangKy",
  BOOKING: "/QuanLyDatVe/LayDanhSachPhongVe",
  CINEMA_CLUSTER: "/QuanLyRap/LayThongTinCumRapTheoHeThong",
  DELETE_MOVIE: "/QuanLyPhim/XoaPhim",
  CREATE_MOVIE: "/QuanLyPhim/ThemPhimUploadHinh",
  BOOKING_SEAT: "/QuanLyDatVe/DatVe",
  USER_PROFILE: "/QuanLyNguoiDung/ThongTinTaiKhoan",
  USER_UPDATE_INFO: "/QuanLyNguoiDung/CapNhatThongTinNguoiDung",
  UPDATE_MOVIE: "/QuanLyPhim/CapNhatPhimUpload",
  SET_MOVIE_SCHEDULE: "/QuanLyDatVe/TaoLichChieu",
  USER_ADD: "/QuanLyNguoiDung/ThemNguoiDung",
  USER_DELETE: "/QuanLyNguoiDung/XoaNguoiDung",
  ALL_USER_INFO: "/QuanLyNguoiDung/LayDanhSachNguoiDung",
  USER_PROFILE_BY_ID: "/QuanLyNguoiDung/LayThongTinNguoiDung",
  SEARCH_USER_BY_ID: "/QuanLyNguoiDung/TimKiemNguoiDung",
};
